# Generated by Django 4.2.3 on 2024-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("uid", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="UID")),
                ("token", models.CharField(max_length=256, verbose_name="값")),
            ],
            options={
                "verbose_name": "디바이스",
                "verbose_name_plural": "디바이스",
                "db_table": "device",
            },
        ),
    ]
