# Generated by Django 4.2.3 on 2024-08-12 14:19

import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import app.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WithdrawalUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=11,
                        validators=[
                            django.core.validators.validate_integer,
                            django.core.validators.MinLengthValidator(10),
                        ],
                        verbose_name="휴대폰",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="가입일")),
            ],
            options={
                "verbose_name": "탈퇴한 유저",
                "verbose_name_plural": "탈퇴한 유저",
                "db_table": "withdrawal_user",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", app.user.models.UserManager()),
            ],
        ),
    ]
