# Generated by Django 4.2.3 on 2024-08-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("text", models.TextField(blank=True, null=True, verbose_name="텍스트")),
                ("image", models.URLField(blank=True, null=True, verbose_name="이미지")),
                (
                    "chat",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.chat", verbose_name="채팅"),
                ),
            ],
            options={
                "verbose_name": "메세지",
                "verbose_name_plural": "메세지",
                "db_table": "message",
                "ordering": ["-created_at"],
            },
        ),
    ]
