# Generated by Django 4.2.3 on 2024-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeleryLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("name", models.CharField(max_length=100, verbose_name="태스크 명")),
                ("task_id", models.CharField(max_length=36, verbose_name="태스크 ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "대기"), ("SUCCESS", "성공"), ("FAILURE", "실패")],
                        default="PENDING",
                        max_length=10,
                        verbose_name="태스크 상태",
                    ),
                ),
                ("message", models.TextField(blank=True, default="", verbose_name="메세지")),
                ("args", models.CharField(blank=True, default=list, max_length=500, verbose_name="태스크 args")),
                ("kwargs", models.CharField(blank=True, default=dict, max_length=500, verbose_name="태스크 kwargs")),
            ],
            options={
                "verbose_name": "셀러리 로그",
                "verbose_name_plural": "셀러리 로그",
                "db_table": "celery_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
