name: Initialize Project
on:
  workflow_dispatch:
  create:
    branches:
      - main

jobs:
  initialize_project:
    runs-on: ubuntu-latest
    steps:
      - name: Set Project Name
        run: |
          echo PROJECT_NAME=$(echo "${{ github.repository }}" | sed "s|${{ github.repository_owner }}\/||g" | sed "s|-django||g") >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Change
        run: |
          sed -i "s|#{PROJECT_NAME}|${PROJECT_NAME}|g" .idea/django.iml
          sed -i "s|#{PROJECT_NAME}|${PROJECT_NAME}|g" .idea/workspace.temp.xml
          sed -i "s|#{PROJECT_NAME}|${PROJECT_NAME}|g" README.md
          sed -i "s|#{PROJECT_NAME}|${PROJECT_NAME}|g" src/config/settings/base.py

      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "initial commit"

      - name: Push
        uses: ad-m/github-push-action@master
