name: CI/CD
on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/sam/src/*.py

jobs:
  continuous_integration:
    if: ${{ !contains(github.event.head_commit.message, 'initial commit') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Environments
        run: |
          echo PROJECT_NAME=$(echo "${{ github.repository }}" | sed "s|${{ github.repository_owner }}\/||g" | sed "s|-django||g") >> $GITHUB_ENV
          echo PROJECT_ENV=$(test ${GITHUB_REF##*/} = main && echo prod || echo dev) >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Websocket Application
        run: |
          sam build -t .github/sam/websocket.yaml

  continuous_deployment:
    runs-on: ubuntu-latest
    needs: [ continuous_integration ]
    steps:
      - name: Set Environments
        run: |
          echo PROJECT_NAME=$(echo "${{ github.repository }}" | sed "s|${{ github.repository_owner }}\/||g" | sed "s|-django||g") >> $GITHUB_ENV
          echo PROJECT_ENV=$(test ${GITHUB_REF##*/} = main && echo prod || echo dev) >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy Websocket Application
        if: steps.changed-lambda.outputs.any_changed == 'true'
        run: |
          sam deploy --stack-name ${{env.PROJECT_NAME}}-${{env.PROJECT_ENV}}-websocket \
            --resolve-s3 \
            --template .github/sam/.aws-sam/build/template.yaml \
            --region ap-northeast-2 \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides ProjectName=${{needs.set_environment.outputs.project_name}} ENV=${{env.PROJECT_ENV}}